### ISSUE TITLE
runner_windows.go signal fix

### ISSUE THREAD

**Issue by nadilas** [contribsys/faktory_worker_go#41]
This code will not compile on Windows (1.3.0-1):

https://github.com/contribsys/faktory_worker_go/blob/de58a756280d12741a9b36e7acc26aa9e639b178/runner_windows.go#L17-L20

But this matches the rest of the package:
```go
	signalMap = map[os.Signal]string{
		SIGTERM: "terminate",
		SIGINT:  "terminate",
	}
```

**Comment by mperham** [comment]
show me the compilation error.

**Comment by nadilas** [comment]
here you go:
```
# github.com/contribsys/faktory_worker_go
..\vendor\github.com\contribsys\faktory_worker_go\runner_windows.go:17:28: undefined: eventType
```
